REPL_CMPL.SRVPGM: private TEXT := repl-rpg Compile Module / Program Objects
REPL_CMPL.SRVPGM: REPL_CMPL.BND REPL_CMPL.MODULE REPL_PM.SRVPGM REPL_USR.SRVPGM

REPL_EVAL.SRVPGM: private TEXT := repl-rpg Evaluate Lines of Code
REPL_EVAL.SRVPGM: REPL_EVAL.BND REPL_EVAL.MODULE REPL_VARS.SRVPGM REPL_INS.SRVPGM

REPL_GEN.SRVPGM: private TEXT := repl-rpg generate source code
REPL_GEN.SRVPGM: REPL_GEN.BND REPL_GEN.MODULE REPL_USR.SRVPGM REPL_VARS.SRVPGM REPL_EVAL.SRVPGM REPL_PSEU.SRVPGM REPL_INS.SRVPGM

REPL_HLPR.SRVPGM: private TEXT := Helpers for REPL Generated Programs
REPL_HLPR.SRVPGM: REPL_HLPR.BND REPL_HLPR.MODULE

REPL_INS.SRVPGM: private TEXT := repl-rpg Add line to generated source
REPL_INS.SRVPGM: REPL_INS.BND REPL_INS.MODULE

REPL_PM.SRVPGM: private TEXT := repl-rpg Program message handling
REPL_PM.SRVPGM: REPL_PM.BND REPL_PM.MODULE

REPL_PSEU.SRVPGM: private TEXT := repl-rpg Edit pseudo code
REPL_PSEU.SRVPGM: REPL_PSEU.BND REPL_PSEU.MODULE REPL_USR.SRVPGM REPL_INS.SRVPGM

REPL_USR.SRVPGM: private TEXT := repl-rpg Perform User Actions
REPL_USR.SRVPGM: REPL_USR.BND REPL_USR.MODULE REPL_PM.SRVPGM

REPL_VARS.SRVPGM: private TEXT := repl-rpg Interrogate Variables
REPL_VARS.SRVPGM: REPL_VARS.BND REPL_VARS.MODULE

REPL.PGM: private ACTGRP := *NEW
REPL.PGM: REPL.MODULE REPL_PM.SRVPGM REPL_CMPL.SRVPGM REPL_PSEU.SRVPGM REPL_GEN.SRVPGM REPL_USR.SRVPGM REPL_INS.SRVPGM

REPLLOAD.PGM: REPLLOAD.MODULE REPL_PSEU.SRVPGM

REPLWRPR.PGM: REPLWRPR.MODULE REPL_CMPL.SRVPGM REPL_EVAL.SRVPGM REPL_GEN.SRVPGM REPL_HLPR.SRVPGM REPL_PSEU.SRVPGM REPL_USR.SRVPGM

REPLPRTR.PGM: REPLPRTR.MODULE REPL_PSEU.SRVPGM

REPLEXEC.PGM: REPLEXEC.MODULE REPL_CMPL.SRVPGM REPL_EVAL.SRVPGM REPL_GEN.SRVPGM REPL_HLPR.SRVPGM REPL_PSEU.SRVPGM REPL_USR.SRVPGM
