REFs := QRPGLEREF.FILE/REPL_HLPR.MBR QRPGLEREF.FILE/REPL_PSEUT.MBR

REPLCMD.MODULE: REPLCMD.SQLRPGLE
REPLLOAD.MODULE: REPLLOAD.RPGLE
REPL_CMPL.MODULE: REPL_CMPL.SQLRPGLE
REPL_EVAL.MODULE: REPL_EVAL.RPGLE
REPL_GEN.MODULE: REPL_GEN.RPGLE
REPL_HLPR.MODULE: REPL_HLPR.SQLRPGLE
REPL_INS.MODULE: REPL_INS.SQLRPGLE
REPL_PM.MODULE: REPL_PM.RPGLE
REPL_PSEU.MODULE: REPL_PSEU.SQLRPGLE
REPL.MODULE: REPL.RPGLE
REPL_USR.MODULE: REPL_USR.RPGLE
REPL_VARS.MODULE: REPL_VARS.SQLRPGLE
REPLWRPR.MODULE: REPLWRPR.SQLRPGLE
REPLPRTR.MODULE: REPLPRTR.SQLRPGLE


QRPGLEREF.FILE:
	$(call echo_cmd,"=== Creating source PF [$(notdir $@)]")
	$(eval crtcmd := CRTSRCPF FILE($(OBJLIB)/$(basename $(@F))) RCDLEN(112) CCSID(37) )
	@$(PRESETUP) \
	$(SCRIPTSPATH)/launch "$(JOBLOGFILE)" "$(crtcmd)" >> $(LOGFILE) 2>&1 && $(call logSuccess,$@) || $(call logFail,$@)

QRPGLEREF.FILE/REPL_HLPR.MBR: $(d)/REPL_HLPR.RPGLEINC | QRPGLEREF.FILE
	$(call echo_cmd,"=== Creating ref member [$(notdir $@)]")
	$(eval crtcmd := CPYFRMSTMF FROMSTMF('$<') TOMBR('/QSYS.LIB/$(OBJLIB).LIB/$@') MBROPT(*REPLACE) )
	@$(PRESETUP) \
	$(SCRIPTSPATH)/launch "$(JOBLOGFILE)" "$(crtcmd)" >> $(LOGFILE) 2>&1 && $(call logSuccess,$@) || $(call logFail,$@)

QRPGLEREF.FILE/REPL_PSEUT.MBR: $(d)/REPL_PSEUT.RPGLEINC | QRPGLEREF.FILE
	$(call echo_cmd,"=== Creating ref member [$(notdir $@)]")
	$(eval crtcmd := CPYFRMSTMF FROMSTMF('$<') TOMBR('/QSYS.LIB/$(OBJLIB).LIB/$@') MBROPT(*REPLACE) )
	@$(PRESETUP) \
	$(SCRIPTSPATH)/launch "$(JOBLOGFILE)" "$(crtcmd)" >> $(LOGFILE) 2>&1 && $(call logSuccess,$@) || $(call logFail,$@)


refs: $(REFs)
all:: refs
